# 1 "C:/MySandboxes/Prodserver/USS/C08_1910/30_CG/CG_USS/20_IMPL/CgTools/Common_C_Tools/InternalTrigger/ItRUT.c"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 10 "<built-in>"




# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "C:/MySandboxes/Prodserver/USS/C08_1910/30_CG/CG_USS/20_IMPL/CgTools/Common_C_Tools/InternalTrigger/ItRUT.c" 2
/* This file contains wrapper functions to Targetlink internal functions for
   execution time and stack consumption measurement. This file serves as source for
   for HCP1_Lib chart "InternalTriggerRUT" which provides it implementations as grahpically
   functions for use in InternalTrigger Scheduling chart.
   
   Author: Steiger, Arthur (extern, I/EF-M2)
*/
# 16 "C:/MySandboxes/Prodserver/USS/C08_1910/30_CG/CG_USS/20_IMPL/CgTools/Common_C_Tools/InternalTrigger/ItRUT.c"
# 1 "C:/MySandboxes/Prodserver/USS/C08_1910/30_CG/CG_USS/20_IMPL/CgTools/Common_C_Tools/InternalTrigger/ITRUT.h" 1



# 1 "C:/MySandboxes/Prodserver/USS/C08_1910/30_CG/CG_USS/20_IMPL/SW_USS/frm\\Platform_Types.h" 1
/**************************************************************************************************\
 *** 
 *** System              : TargetLink Simulation RTE
 *** ECU                 : TL_ECU
 *** Configuration       : NONE
 *** Codefile            : Platform_Types.h
 ***
 *** Generated by the SystemDesk RTE code generator
 *** Generation date: 2024-12-05 09:37:05
 ***
 *** SystemDesk version  : 4.3.0.314576
 *** Copyright (c) 2016 dSPACE GmbH
\**************************************************************************************************/




/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/


/* CPU types. */




/* Bit ordering. */



/* Byte ordering. */



/* CPU. */




/* Definitions for TRUE and FALSE. */






/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/


/* Integer data types. */
typedef unsigned char boolean;/* AUTOSAR type used together with the definitions TRUE and FALSE. */
typedef unsigned char uint8;/* The standard AUTOSAR type for 8 bit unsigned integer */
typedef unsigned short int uint16;/* The standard AUTOSAR type for 16 bit unsigned integer */
typedef unsigned long int uint32;/* The standard AUTOSAR type for 32 bit unsigned integer */
typedef char sint8;/* The standard AUTOSAR type for 8 bit signed integer */
typedef short int sint16;/* The standard AUTOSAR type for 16 bit signed integer */
typedef long int sint32;/* The standard AUTOSAR type for 32 bit signed integer */

/* Optimized integer data types. */
typedef unsigned long int uint8_least;/* The optimized AUTOSAR type for 8 bit unsigned integer */
typedef unsigned long int uint16_least;/* The optimized AUTOSAR type for 16 bit unsigned integer */
typedef unsigned long int uint32_least;/* The optimized AUTOSAR type for 32 bit unsigned integer */
typedef long int sint8_least;/* The optimized AUTOSAR type for 8 bit signed integer */
typedef long int sint16_least;/* The optimized AUTOSAR type for 16 bit signed integer */
typedef long int sint32_least;/* The optimized AUTOSAR type for 32 bit signed integer */

/* Floating point types. */
typedef float float32;/* The standard AUTOSAR type for 32 bit floating-point number */
typedef double float64;/* The standard AUTOSAR type for 64 bit floating-point number */
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/



/*----------------------------------------------------------------------------*\
 END OF FILE
\*----------------------------------------------------------------------------*/
# 5 "C:/MySandboxes/Prodserver/USS/C08_1910/30_CG/CG_USS/20_IMPL/CgTools/Common_C_Tools/InternalTrigger/ITRUT.h" 2

void ITInitRUT(void);

uint32 ITGetWatch(void);
uint32 ITGetStack(void);
# 17 "C:/MySandboxes/Prodserver/USS/C08_1910/30_CG/CG_USS/20_IMPL/CgTools/Common_C_Tools/InternalTrigger/ItRUT.c" 2

void ITInitRUT(void)
{
# 29 "C:/MySandboxes/Prodserver/USS/C08_1910/30_CG/CG_USS/20_IMPL/CgTools/Common_C_Tools/InternalTrigger/ItRUT.c"
}

uint32 ITGetWatch(void)
{





  return 0;

}

uint32 ITGetStack(void)
{



  return 0;

}
